#!/usr/bin/with-contenv sh
#shellcheck shell=sh

/usr/sbin/lighttpd -tt -f /etc/lighttpd/lighttpd.conf || exit 0

/usr/sbin/lighttpd \
    -f /etc/lighttpd/lighttpd.conf \
    -D \
    2>&1 | awk -W Interactive '{print "[lighttpd] " $0}'
